baseURL = ""
languageCode = "en-us"
title = "Shortbread"
theme = "hugo-theme-docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = true

[params]
ordersectionsby = "weight"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
