baseURL = ""
languageCode = "en-us"
title = "Shortbread"
theme = "hugo-theme-docdock"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false
enableRobotsTXT = false

[params]
ordersectionsby = "weight"
description = "A free & simple Vector Tile schema for OpenStreetMap"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true # Allow HTML in Markdown

